name: Run VSCode Extension Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Compile
        run: yarn compile

      - name: Run tests
        run: xvfb-run -a yarn test
        if: runner.os == 'Linux'

      - name: Run tests
        run: yarn test
        if: runner.os != 'Linux'
